// gestion/src/redux/actions/actionTypes.js

// Clientes
export const GET_CLIENTES_REQUEST = 'GET_CLIENTES_REQUEST';
export const GET_CLIENTES_SUCCESS = 'GET_CLIENTES_SUCCESS';
export const GET_CLIENTES_FAIL = 'GET_CLIENTES_FAIL';

export const ADD_CLIENTE_REQUEST = 'ADD_CLIENTE_REQUEST';
export const ADD_CLIENTE_SUCCESS = 'ADD_CLIENTE_SUCCESS';
export const ADD_CLIENTE_FAIL = 'ADD_CLIENTE_FAIL';

export const UPDATE_CLIENTE_REQUEST = 'UPDATE_CLIENTE_REQUEST';
export const UPDATE_CLIENTE_SUCCESS = 'UPDATE_CLIENTE_SUCCESS';
export const UPDATE_CLIENTE_FAIL = 'UPDATE_CLIENTE_FAIL';

export const DELETE_CLIENTE_REQUEST = 'DELETE_CLIENTE_REQUEST';
export const DELETE_CLIENTE_SUCCESS = 'DELETE_CLIENTE_SUCCESS';
export const DELETE_CLIENTE_FAIL = 'DELETE_CLIENTE_FAIL';

// Tipos para obtener un cliente por ID
export const GET_CLIENTE_BY_ID_REQUEST = 'GET_CLIENTE_BY_ID_REQUEST';
export const GET_CLIENTE_BY_ID_SUCCESS = 'GET_CLIENTE_BY_ID_SUCCESS';
export const GET_CLIENTE_BY_ID_FAIL = 'GET_CLIENTE_BY_ID_FAIL';

// Tipo para resetear el estado del cliente seleccionado
export const RESET_SELECTED_CLIENT = 'RESET_SELECTED_CLIENT';
// Productos
export const GET_PRODUCTOS_REQUEST = 'GET_PRODUCTOS_REQUEST';
export const GET_PRODUCTOS_SUCCESS = 'GET_PRODUCTOS_SUCCESS';
export const GET_PRODUCTOS_FAIL = 'GET_PRODUCTOS_FAIL';

export const ADD_PRODUCTO_REQUEST = 'ADD_PRODUCTO_REQUEST';
export const ADD_PRODUCTO_SUCCESS = 'ADD_PRODUCTO_SUCCESS';
export const ADD_PRODUCTO_FAIL = 'ADD_PRODUCTO_FAIL';

export const UPDATE_PRODUCTO_REQUEST = 'UPDATE_PRODUCTO_REQUEST';
export const UPDATE_PRODUCTO_SUCCESS = 'UPDATE_PRODUCTO_SUCCESS';
export const UPDATE_PRODUCTO_FAIL = 'UPDATE_PRODUCTO_FAIL';

export const DELETE_PRODUCTO_REQUEST = 'DELETE_PRODUCTO_REQUEST';
export const DELETE_PRODUCTO_SUCCESS = 'DELETE_PRODUCTO_SUCCESS';
export const DELETE_PRODUCTO_FAIL = 'DELETE_PRODUCTO_FAIL';

// Stock
export const GET_STOCK_REQUEST = 'GET_STOCK_REQUEST';
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';
export const GET_STOCK_FAIL = 'GET_STOCK_FAIL';

export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST'; // Usado para la acción POST (añadir/sumar)
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_FAIL = 'ADD_STOCK_FAIL';

export const UPDATE_STOCK_REQUEST = 'UPDATE_STOCK_REQUEST'; // Usado para la acción PUT (actualizar registro específico)
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS';
export const UPDATE_STOCK_FAIL = 'UPDATE_STOCK_FAIL';

export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_FAIL = 'DELETE_STOCK_FAIL';

// Ventas (agrega estos si aún no están)
export const GET_VENTAS_REQUEST = 'GET_VENTAS_REQUEST';
export const GET_VENTAS_SUCCESS = 'GET_VENTAS_SUCCESS';
export const GET_VENTAS_FAIL = 'GET_VENTAS_FAIL';

export const ADD_VENTA_REQUEST = 'ADD_VENTA_REQUEST';
export const ADD_VENTA_SUCCESS = 'ADD_VENTA_SUCCESS';
export const ADD_VENTA_FAIL = 'ADD_VENTA_FAIL';

export const UPDATE_VENTA_REQUEST = 'UPDATE_VENTA_REQUEST';
export const UPDATE_VENTA_SUCCESS = 'UPDATE_VENTA_SUCCESS';
export const UPDATE_VENTA_FAIL = 'UPDATE_VENTA_FAIL';

export const DELETE_VENTA_REQUEST = 'DELETE_VENTA_REQUEST';
export const DELETE_VENTA_SUCCESS = 'DELETE_VENTA_SUCCESS';
export const DELETE_VENTA_FAIL = 'DELETE_VENTA_FAIL';

//Detalles de venta
export const GET_DETALLES_VENTA_REQUEST = 'GET_DETALLES_VENTA_REQUEST';
export const GET_DETALLES_VENTA_SUCCESS = 'GET_DETALLES_VENTA_SUCCESS';
export const GET_DETALLES_VENTA_FAIL = 'GET_DETALLES_VENTA_FAIL';
export const ADD_DETALLE_VENTA_REQUEST = 'ADD_DETALLE_VENTA_REQUEST';
export const ADD_DETALLE_VENTA_SUCCESS = 'ADD_DETALLE_VENTA_SUCCESS';
export const ADD_DETALLE_VENTA_FAIL = 'ADD_DETALLE_VENTA_FAIL';
export const UPDATE_DETALLE_VENTA_REQUEST = 'UPDATE_DETALLE_VENTA_REQUEST';
export const UPDATE_DETALLE_VENTA_SUCCESS = 'UPDATE_DETALLE_VENTA_SUCCESS';
export const UPDATE_DETALLE_VENTA_FAIL = 'UPDATE_DETALLE_VENTA_FAIL';

// Proveedores
export const GET_PROVEEDORES_REQUEST = 'GET_PROVEEDORES_REQUEST';
export const GET_PROVEEDORES_SUCCESS = 'GET_PROVEEDORES_SUCCESS';
export const GET_PROVEEDORES_FAIL = 'GET_PROVEEDORES_FAIL';

export const ADD_PROVEEDOR_REQUEST = 'ADD_PROVEEDOR_REQUEST';
export const ADD_PROVEEDOR_SUCCESS = 'ADD_PROVEEDOR_SUCCESS';
export const ADD_PROVEEDOR_FAIL = 'ADD_PROVEEDOR_FAIL';

export const UPDATE_PROVEEDOR_REQUEST = 'UPDATE_PROVEEDOR_REQUEST';
export const UPDATE_PROVEEDOR_SUCCESS = 'UPDATE_PROVEEDOR_SUCCESS';
export const UPDATE_PROVEEDOR_FAIL = 'UPDATE_PROVEEDOR_FAIL';

export const DELETE_PROVEEDOR_REQUEST = 'DELETE_PROVEEDOR_REQUEST';
export const DELETE_PROVEEDOR_SUCCESS = 'DELETE_PROVEEDOR_SUCCESS';
export const DELETE_PROVEEDOR_FAIL = 'DELETE_PROVEEDOR_FAIL';
